SELECT
  SQL
FROM
  sqlite_schema
WHERE
  name='indicators';

CREATE TABLE
  indicators2 (
    "Ticker_Symbol" TEXT,
    "Period_Ending" TEXT,
    "Accounts_Payable" REAL,
    "Accounts_Receivable" REAL,
    "Add_l_income_expense_items" REAL,
    "After_Tax_ROE" REAL,
    "Capital_Expenditures" REAL,
    "Capital_Surplus" REAL,
    "Cash_Ratio" REAL,
    "Cash_and_Cash_Equivalents" REAL,
    "Changes_in_Inventories" REAL,
    "Common_Stocks" REAL,
    "Cost_of_Revenue" REAL,
    "Current_Ratio" REAL,
    "Deferred_Asset_Charges" REAL,
    "Deferred_Liability_Charges" REAL,
    "Depreciation" REAL,
    "Earnings_Before_Interest_and_Tax" REAL,
    "Earnings_Before_Tax" REAL,
    "Effect_of_Exchange_Rate" REAL,
    "Equity_Earnings_Loss_Unconsolidated_Subsidiary" REAL,
    "Fixed_Assets" REAL,
    "Goodwill" REAL,
    "Gross_Margin" REAL,
    "Gross_Profit" REAL,
    "Income_Tax" REAL,
    "Intangible_Assets" REAL,
    "Interest_Expense" REAL,
    "Inventory" REAL,
    "Investments" REAL,
    "Liabilities" REAL,
    "Long_Term_Debt" REAL,
    "Long_Term_Investments" REAL,
    "Minority_Interest" REAL,
    "Misc__Stocks" REAL,
    "Net_Borrowings" REAL,
    "Net_Cash_Flow" REAL,
    "Net_Cash_Flow_Operating" REAL,
    "Net_Cash_Flows_Financing" REAL,
    "Net_Cash_Flows_Investing" REAL,
    "Net_Income" REAL,
    "Net_Income_Adjustments" REAL,
    "Net_Income_Applicable_to_Common_Shareholders" REAL,
    "Net_Income_Cont__Operations" REAL,
    "Net_Receivables" REAL,
    "Non_Recurring_Items" REAL,
    "Operating_Income" REAL,
    "Operating_Margin" REAL,
    "Other_Assets" REAL,
    "Other_Current_Assets" REAL,
    "Other_Current_Liabilities" REAL,
    "Other_Equity" REAL,
    "Other_Financing_Activities" REAL,
    "Other_Investing_Activities" REAL,
    "Other_Liabilities" REAL,
    "Other_Operating_Activities" REAL,
    "Other_Operating_Items" REAL,
    "Pre_Tax_Margin" REAL,
    "Pre_Tax_ROE" REAL,
    "Profit_Margin" REAL,
    "Quick_Ratio" REAL,
    "Research_and_Development" REAL,
    "Retained_Earnings" REAL,
    "Sale_and_Purchase_of_Stock" REAL,
    "Sales__General_and_Admin_" REAL,
    "Short_Term_Debt___Current_Portion_of_Long_Term_Debt" REAL,
    "Short_Term_Investments" REAL,
    "Total_Assets" REAL,
    "Total_Current_Assets" REAL,
    "Total_Current_Liabilities" REAL,
    "Total_Equity" REAL,
    "Total_Liabilities" REAL,
    "Total_Liabilities___Equity" REAL,
    "Total_Revenue" REAL,
    "For_Year" REAL,
    "Earnings_Per_Share" REAL,
    "Estimated_Shares_Outstanding" REAL
  );